version: "3.9"  
services:
  api:
    build: .
    depends_on:
      - db
    ports: 
    - "5050:5050"
  
  db:
    hostname: db
    build: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54321:5432'